#!/bin/sh

# send expiration via email without color codes
# sh expiration_dates | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed "s/\x0f//g" > output ; mail -s "SSL Certificate expiration dates" "oppermann.lukas@gmail.com" < output

live_dir=/home/letsencrypt/live/

echo "############"
echo " "
for d in $(find $live_dir*/ -maxdepth 1 -type d);
do
  cert="${d}cert.pem"
  site=${d##$live_dir}
  if openssl x509 -checkend 86400 -noout -in $cert
  then
    echo "\033[1;92m✔︎\033[0m The certificate $site is good for at least another day!"
    today=`date +%D`
    expiredate=`openssl x509 -enddate -noout -in $cert  | awk -F'=' '{print $2}'`
    expdate="date +%D --date='$expiredate'"
    ed=`eval $expdate`
    daysleft=`echo $(($(($(date -u -d "$ed" "+%s") - $(date -u -d "$today" "+%s"))) / 86400))`
    echo "Today's date: $today, expiring on: \033[1;35m$ed\033[0m, \033[1;35m$daysleft\033[0m days left to go."
  else
    echo "\033[1;92m⨯\033[0m The certificate $cert has expired or will do so within 24 hours!"
    echo "(or is invalid/not found)"
  fi
  echo " "
done
echo "############"
