#!/bin/sh

docker run -it --rm --name letsencrypt \
  -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
  --volumes-from nginx \
  quay.io/letsencrypt/letsencrypt \
  renew \
  --text \
  --staging \
  --dry-run
